version: '3.7'
services:
    mongodb2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mongodb-customer2
        restart: always
        ports:
            - 12500:27017
        volumes:
            - ./mongo/:/etc/mongo
        networks: 
            app_subnet:
                ipv4_address: 172.16.1.5
networks:
    app_subnet:
        external: true
volumes:
    mongo: {}
    