server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**